### ISSUE TITLE
Possible XSS vulnerablity

### ISSUE THREAD

**Issue by ThePaulMcBride** [mghignet/jwt-flash-messages#2]
I might be wrong,  but because data from the cookie is rendered straight to the screen, is there not the possibility that a malicious user may tamper with the cookie?

If so, I'll create a pull request that escapes any HTML in the flash message.

**Comment by ThePaulMcBride** [comment]
@mghignet Have you had any thoughts on this?

**Comment by mghignet** [comment]
Hi !
Sorry about the delay. It seems that you're right. Do you still want to create a pull request on this?
Thank you for reporting this.

**Comment by ThePaulMcBride** [comment]
Not a problem. I'll do this tonight. I'm planning to pull in a package to escaping any user input before it is attached to the response. Happy with that?

**Comment by mghignet** [comment]
Yes that sounds nice. Thanks!
